name: Convert Markdown Resumes to PDF

on:
  # Trigger when any file is pushed to the main branch
  push:
    branches:
      - main

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Ensure the `resumes` folder exists
      - name: Verify resumes folder
        run: |
          if [ ! -d "resumes" ]; then
            echo "Error: 'resumes' folder does not exist."
            exit 1
          fi

      # Step 3: Install Pandoc and LaTeX
      - name: Install Pandoc and LaTeX
        run: sudo apt-get update && sudo apt-get install -y pandoc texlive-xetex

      # Step 4: Convert Markdown files to PDFs
      - name: Convert Markdown to PDF
        run: |
          for file in resumes/*.md; do
            echo "Converting $file to PDF..."
            pandoc "$file" -o "${file%.md}.pdf" --pdf-engine=xelatex
          done

      # Step 5: Commit and Push PDFs
      - name: Commit and Push PDFs
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add resumes/*.pdf
          git commit -m "chore: add or update PDFs for resumes"
          git push
