name: Convert Markdown Resumes to PDF

on:
  workflow_dispatch: # Manual trigger for existing files
  push:              # Automatic trigger for changes to resumes/*.md files
    branches:
      - main
    paths:
      - 'resumes/*.md'

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install Pandoc and LaTeX
      - name: Install Pandoc and LaTeX
        run: sudo apt-get update && sudo apt-get install -y pandoc texlive-xetex

      # Step 3: Convert all Markdown files in 'resumes' to PDFs
      - name: Convert Markdown to PDF
        run: |
          for file in resumes/*.md; do
            echo "Converting $file to PDF..."
            pandoc "$file" -o "${file%.md}.pdf" --pdf-engine=xelatex
          done

      # Step 4: Commit and push generated PDFs back to the repository
      - name: Commit and Push PDFs
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add resumes/*.pdf
          git commit -m "chore: add or update PDFs for resumes"
          git push
