name: Convert Markdown to PDF and Commit to Repository

on:
  push:
    paths:
      - 'resume/*.md'
  workflow_dispatch:

jobs:
  convert-md-to-pdf:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Install Pandoc and LaTeX for PDF generation
      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y pandoc texlive-xetex

      # Convert Markdown files in the resume folder to PDF
      - name: Convert Markdown to PDF
        run: |
          for file in resume/*.md; do
            pandoc "$file" -o "${file%.md}.pdf";
          done

      # Commit the generated PDFs back to the repository
      - name: Commit and Push PDFs
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add resume/*.pdf
          git commit -m "chore: add generated PDFs from Markdown files"
          git push
